name: SimpleBountySystem
version: 1.1-Release
main: cloud.stivenfocs.SimpleBountySystem.Loader
authors: [StivenFocs]
softdepend: [Vault,PlaceholderAPI]
description: "Simple but High Configurable BountySystem plugin"
commands:
  simplebountysystem:
    aliases: [sbs]
    description: "Main command of the SimpleBountySystem plugin"
permissions:
  simplebountysystem.bounty:
    default: true

  simplebountysystem.admin:
    default: op

  simplebountysystem.*:
    children:
      simplebountysystem.bounty: true
      simplebountysystem.admin: true